-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

delete from Host where 1=1;
ALTER TABLE Host ADD UNIQUE unique_index(IPAddress, portNumber);
ALTER TABLE Host AUTO_INCREMENT=1;

delete from Involves where 1=1;
ALTER TABLE Involves ADD UNIQUE unique_index(sourceID, destinationID);
ALTER TABLE Involves AUTO_INCREMENT=1;

delete from WebService where 1=1;

delete from Protocol where 1=1;
ALTER TABLE Protocol AUTO_INCREMENT=1;

delete from FlowStats where 1=1;
ALTER TABLE FlowStats AUTO_INCREMENT=1;

delete from Flow where 1=1;
ALTER TABLE Flow AUTO_INCREMENT=1;

delete from DirectionalFlagCounts where 1=1;
ALTER TABLE DirectionalFlagCounts AUTO_INCREMENT=1;

delete from TotalFlagCounts where 1=1;
ALTER TABLE TotalFlagCounts AUTO_INCREMENT=1;

delete from ForwardStats where 1=1;
ALTER TABLE ForwardStats AUTO_INCREMENT=1;

delete from BackwardStats where 1=1;
ALTER TABLE BackwardStats AUTO_INCREMENT=1;

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

LOAD DATA INFILE
'/var/lib/mysql-files/21-Network-Traffic/Dataset-Unicauca-Version2-87Atts.csv'
ignore into table Host 
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 3577290 LINES (
    @dummy,
    IPAddress,
    portNumber,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy
);

LOAD DATA INFILE
'/var/lib/mysql-files/21-Network-Traffic/Dataset-Unicauca-Version2-87Atts.csv'
ignore into table Host 
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 3577290 LINES (
    @dummy,
    @dummy,
    @dummy,
    IPAddress,
    portNumber,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy
);

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

LOAD DATA INFILE
'/var/lib/mysql-files/21-Network-Traffic/Dataset-Unicauca-Version2-87Atts.csv'
ignore into table Involves 
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 3577290 LINES (
    @dummy,
    @S_IP,
    @S_Port,
    @D_IP,
    @D_Port,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy
)
set 
    sourceID = (select hostID from Host where IPAddress = @S_IP and portNumber = @S_Port),
    destinationID = (select hostID from Host where IPAddress = @D_IP and portNumber = @D_Port);

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

LOAD DATA INFILE
'/var/lib/mysql-files/21-Network-Traffic/Dataset-Unicauca-Version2-87Atts.csv'
ignore into table WebService 
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 3577290 LINES (
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    L7Protocol,
    L7protocolName
);

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

LOAD DATA INFILE
'/var/lib/mysql-files/21-Network-Traffic/Dataset-Unicauca-Version2-87Atts.csv'
ignore into table Protocol 
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 3577290 LINES (
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    protocolID,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy
)
set protocolName = (select 'TCP');

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

LOAD DATA INFILE
'/var/lib/mysql-files/21-Network-Traffic/Dataset-Unicauca-Version2-87Atts.csv'
ignore into table FlowStats 
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 3577290 LINES (
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @TIMEVAR_timestamp,
    flowDuration,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    flowBytesS,
    flowPacketsS,
    flowIATMean,
    flowIATStd,
    flowIATMax,
    flowIATMin,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    minPacketLength,
    maxPacketLength,
    packetLengthMean,
    packetLengthStd,
    packetLengthVariance,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    downUpRatio,
    averagePacketSize,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    activeMean,
    activeStd,
    activeMax,
    activeMin,
    idleMean,
    idleStd,
    idleMax,
    idleMin,
    @dummy,
    @dummy,
    @dummy
)
set timestamp = STR_TO_DATE(@TIMEVAR_timestamp, "%d/%m/%Y%T")
;

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

LOAD DATA INFILE
'/var/lib/mysql-files/21-Network-Traffic/Dataset-Unicauca-Version2-87Atts.csv'
ignore into table Flow 
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 3577290 LINES (
    @dummy,
    @S_IP,
    @S_Port,
    @D_IP,
    @D_Port,
    protocolID,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    label,
    L7Protocol,
    @dummy
)

set 
    connectionID = (
        select connectionID from Involves 
        where sourceID = (
            select hostID from Host 
            where IPAddress=@S_IP 
            and portNumber=@S_Port
        ) 
        and destinationID = (
            select hostID from Host 
            where IPAddress=@D_IP 
            and portNumber=@D_Port
        )
    )
;

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

LOAD DATA INFILE
'/var/lib/mysql-files/21-Network-Traffic/Dataset-Unicauca-Version2-87Atts.csv'
ignore into table DirectionalFlagCounts 
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 3577290 LINES (
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    fwdPSHFlags,
    bwdPSHFlags,
    fwdURGFlags,
    bwdURGFlags,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy
);

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

LOAD DATA INFILE
'/var/lib/mysql-files/21-Network-Traffic/Dataset-Unicauca-Version2-87Atts.csv'
ignore into table TotalFlagCounts 
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 3577290 LINES (
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    FINFlagCount,
    SYNFlagCount,
    RSTFlagCount,
    PSHFlagCount,
    ACKFlagCount,
    URGFlagCount,
    CWEFlagCount,
    ECEFlagCount,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy
);

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

LOAD DATA INFILE
'/var/lib/mysql-files/21-Network-Traffic/Dataset-Unicauca-Version2-87Atts.csv'
ignore into table ForwardStats 
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 3577290 LINES (
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    totalFwdPackets,
    @dummy,
    totalLengthFwdPackets,
    @dummy,
    fwdPacketLengthMax,
    fwdPacketLengthMin,
    fwdPacketLengthMean,
    fwdPacketLengthStd,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    fwdIATTotal,
    fwdIATMean,
    fwdIATStd,
    fwdIATMax,
    fwdIATMin,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    fwdHeaderLength,
    @dummy,
    fwdPackets_s,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    avgFwdSegmentSize,
    @dummy,
    @dummy,
    fwdAvgBytesBulk,
    fwdAvgPacketsBulk,
    fwdAvgBulkRate,
    @dummy,
    @dummy,
    @dummy,
    subflowFwdPackets,
    subflowFwdBytes,
    @dummy,
    @dummy,
    init_Win_bytes_forward,
    @dummy,
    act_data_pkt_fwd,
    min_seg_size_forward,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy
);

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

LOAD DATA INFILE
'/var/lib/mysql-files/21-Network-Traffic/Dataset-Unicauca-Version2-87Atts.csv'
ignore into table BackwardStats 
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 3577290 LINES (
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    totalBackwardPackets,
    @dummy,
    totalLengthBwdPackets,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    bwdPacketLengthMax,
    bwdPacketLengthMin,
    bwdPacketLengthMean,
    bwdPacketLengthStd,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    bwdIATTotal,
    bwdIATMean,
    bwdIATStd,
    bwdIATMax,
    bwdIATMin,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    bwdHeaderLength,
    @dummy,
    bwdPackets_s,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    avgBwdSegmentSize,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    bwdAvgBytesBulk,
    bwdAvgPacketsBulk,
    bwdAvgBulkRate,
    @dummy,
    @dummy,
    subflowBwdPackets,
    subflowBwdBytes,
    @dummy,
    init_Win_bytes_backward,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy,
    @dummy
);

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~